# Start app from port 80
FROM golang:1.8-onbuild
MAINTAINER lucas.feijo@resultadosdigitais.com.br

# docker build -t <name> . 
# docker run -d -p 80:80 <name>

# to push an image on docker hub
# docker tag <image-ID> <docker hub username>/<image name>:<version label or tag>
# docker login
# docker push <docker hub username>/<image name>